### ISSUE TITLE
issue with DAE

### ISSUE THREAD

**Issue by jingyonglin** [BorealisAI/SLAPS-GNN#2]
compare the generated features with original features, the size must match.
so at model.py
line 30:   
self.layers.append(GCNConv_dense(hidden_dim, nclasses))

think it should be 
self.layers.append(GCNConv_dense(hidden_dim, in_dim))

**Comment by baharefatemi** [comment]
The size match as when creating an instance of a GCN_DAE in lines 229 and 162 in main.py, both in_dim and n_classes are set to nfeats. The reason why not use only one parameter for both is to keep the model general.
